version: "3.7"

services:
  postgresql:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
    ports:
      - 5432:5432
    networks:
      - coffeeshop-network

  plantuml-server:
    image: "plantuml/plantuml-server:jetty"
    environment:
      PLANTUML_LIMIT_SIZE: 24384
    ports:
      - 8080:8080
    networks:
      - coffeeshop-network

  coffeeshop-app:
    image: ghcr.io/thangchung/coffeeshop-modular/coffeeshop-app:0.1.0
    build:
      context: .
      dockerfile: ./src/coffeeshop/Dockerfile
    environment:
      - ConnectionStrings__coffeeshopdb=Server=postgresql;Port=5432;Database=postgres;User Id=postgres;Password=P@ssw0rd
    ports:
      - "5000:80"
    depends_on:
      - postgresql
    networks:
      - coffeeshop-network

networks:
  coffeeshop-network: