@startuml coffeeshop_software_system

' left to right direction
' skinparam packageStyle rect

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
' uncomment the following line and comment the first to use locally
' !include C4_Context.puml

LAYOUT_TOP_DOWN()
SHOW_PERSON_OUTLINE()
' LAYOUT_AS_SKETCH()
' LAYOUT_WITH_LEGEND()

title System Context Diagram for Coffee Shop

Person(normal_user, "Normal User", "A user buys coffee and foods")

Boundary(c0, "Coffee Shop Application") {
    System(coffeeshop_app, "The coffee shop application", "This application serves the coffee, drinks and foods and uses by counter, barista and kitchen modules.")
}

Rel(normal_user, coffeeshop_app, "Uses", "REST/JSON")

@enduml